#!/bin/bash
#
# make-samples.sh — regenerate samples.inc, the JPEG and GIF images the
# packages example decodes on the board.
#
# fcl-image can write BMP and PNG, so those two formats are made on the board
# itself and read straight back. It has no JPEG or GIF writer that this build
# carries, so the only way to prove those two readers on hardware is to take a
# picture with it that was made somewhere else. These are that picture: a solid
# red 16x16 JPEG and an 8x8 red/green checker GIF, small enough to sit in the
# kernel image as two byte arrays.
#
# Needs python3 and sips, both of which macOS has as standard. Run it from this
# directory. samples.inc is checked in; this script exists so it can be made
# again rather than only inherited.
#
set -eu
cd "$(dirname "$0")"
TMP="$(mktemp -d)"
trap 'rm -rf "$TMP"' EXIT

python3 - "$TMP" <<'PY'
import struct, sys, os
tmp = sys.argv[1]

def bmp(path, w, h, fn):
    rows = []
    for y in range(h):
        row = b''
        for x in range(w):
            row += bytes(fn(x, y))          # BGR, bottom-up
        row += b'\x00' * ((4 - (len(row) % 4)) % 4)
        rows.append(row)
    pix = b''.join(reversed(rows))
    hdr = (b'BM' + struct.pack('<IHHI', 14 + 40 + len(pix), 0, 0, 54)
           + struct.pack('<IiiHHIIiiII', 40, w, h, 1, 24, 0, len(pix),
                         2835, 2835, 0, 0))
    open(path, 'wb').write(hdr + pix)

# Solid red for the JPEG: JPEG is lossy and chroma-subsampled, so a checker
# comes back smeared and no pixel value can be asserted. A solid block decodes
# to within a hair of the colour that went in.
bmp(os.path.join(tmp, 'solid.bmp'), 16, 16, lambda x, y: (0, 0, 255))
# A checker for the GIF: lossless, so every pixel is exact and the reader's
# palette and interlace handling are both exercised.
bmp(os.path.join(tmp, 'check.bmp'), 8, 8,
    lambda x, y: (0, 0, 255) if (x + y) % 2 == 0 else (0, 255, 0))
PY

sips -s format jpeg "$TMP/solid.bmp" --out "$TMP/sample.jpg" > /dev/null
sips -s format gif  "$TMP/check.bmp" --out "$TMP/sample.gif" > /dev/null

python3 - "$TMP" > samples.inc <<'PY'
import sys, os
tmp = sys.argv[1]

def emit(name, path, note):
    data = open(path, 'rb').read()
    print('{ %s }' % note)
    print('const')
    print('  %s: array[0..%d] of byte = (' % (name, len(data) - 1))
    for i in range(0, len(data), 12):
        chunk = ', '.join('$%02x' % b for b in data[i:i + 12])
        end = ',' if i + 12 < len(data) else ');'
        print('    ' + chunk + end)
    print()

print('{ samples.inc — generated by make-samples.sh, do not edit by hand.')
print()
print('  Two pictures made off the board, so the JPEG and GIF readers have')
print('  something real to decode. fcl-image in this build writes neither')
print('  format, so they cannot be made on the board and read back the way')
print('  the BMP and PNG rungs do. }')
print()
emit('SampleJPEG', os.path.join(tmp, 'sample.jpg'),
     'A solid red 16x16 JPEG. Every pixel decodes to near $FF00 red.')
emit('SampleGIF', os.path.join(tmp, 'sample.gif'),
     'An 8x8 red/green checker GIF. Lossless: every pixel is exact.')
PY

echo "samples.inc: $(grep -c '' samples.inc) lines"
